name: Bruce Makes Things
favicon: null
layout_spectrum: 0.8974
typography_spectrum: 0.34921684651635587
title: Working Hands
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0d9e0'
    - '#08070d'
    - '#b2bbc4'
    - '#2f3130'
    - '#4f4f4d'
  brandStrength: 0.5625
  lightness: 0.9493835202883929
  saturation: 0.31465203617699444
  rhythmicContrast: 0.4275440427009016
purpose: []
