name: Bruce Makes Things
favicon: null
layout_spectrum: 0.8694021594710648
typography_spectrum: 0.34921684651635587
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5432116398587823
  lightness: 0.9493835202883929
  saturation: 0.31465203617699444
  rhythmicContrast: 0.4275440427009016
purpose: []
